#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Adds the current directory to the library path
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DIR

java -cp $DIR/path-pattern-finder.jar:$DIR/../lib/* -Xms500m -Xmx16000m -Djava.awt.headless=true com.owenfeehan.pathpatternfinder.PathPatternFinder "$@"
